export default {
	login: 'Arun1nly1',
	id: 33782362,
	node_id: 'MDQ6VXNlcjMzNzgyMzYy',
	avatar_url: 'https://avatars.githubusercontent.com/u/33782362?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/Arun1nly1',
	html_url: 'https://github.com/Arun1nly1',
	followers_url: 'https://api.github.com/users/Arun1nly1/followers',
	following_url:
		'https://api.github.com/users/Arun1nly1/following{/other_user}',
	gists_url: 'https://api.github.com/users/Arun1nly1/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/Arun1nly1/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/Arun1nly1/subscriptions',
	organizations_url: 'https://api.github.com/users/Arun1nly1/orgs',
	repos_url: 'https://api.github.com/users/Arun1nly1/repos',
	events_url: 'https://api.github.com/users/Arun1nly1/events{/privacy}',
	received_events_url: 'https://api.github.com/users/Arun1nly1/received_events',
	type: 'User',
	site_admin: false,
	name: 'Arun',
	company: 'MY OWN COMPANY',
	blog: '',
	location: null,
	email: null,
	hireable: true,
	bio: 'A learner',
	twitter_username: null,
	public_repos: 52,
	public_gists: 0,
	followers: 11,
	following: 18,
	created_at: '2017-11-18T12:12:33Z',
	updated_at: '2021-10-14T14:37:05Z',
}
