export default [
	{
		login: 'crzyzenn',
		id: 25949428,
		node_id: 'MDQ6VXNlcjI1OTQ5NDI4',
		avatar_url: 'https://avatars.githubusercontent.com/u/25949428?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/crzyzenn',
		html_url: 'https://github.com/crzyzenn',
		followers_url: 'https://api.github.com/users/crzyzenn/followers',
		following_url:
			'https://api.github.com/users/crzyzenn/following{/other_user}',
		gists_url: 'https://api.github.com/users/crzyzenn/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/crzyzenn/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/crzyzenn/subscriptions',
		organizations_url: 'https://api.github.com/users/crzyzenn/orgs',
		repos_url: 'https://api.github.com/users/crzyzenn/repos',
		events_url: 'https://api.github.com/users/crzyzenn/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/crzyzenn/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'samarajyastha',
		id: 29505124,
		node_id: 'MDQ6VXNlcjI5NTA1MTI0',
		avatar_url: 'https://avatars.githubusercontent.com/u/29505124?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/samarajyastha',
		html_url: 'https://github.com/samarajyastha',
		followers_url: 'https://api.github.com/users/samarajyastha/followers',
		following_url:
			'https://api.github.com/users/samarajyastha/following{/other_user}',
		gists_url: 'https://api.github.com/users/samarajyastha/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/samarajyastha/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/samarajyastha/subscriptions',
		organizations_url: 'https://api.github.com/users/samarajyastha/orgs',
		repos_url: 'https://api.github.com/users/samarajyastha/repos',
		events_url: 'https://api.github.com/users/samarajyastha/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/samarajyastha/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'Saurabstha',
		id: 29506421,
		node_id: 'MDQ6VXNlcjI5NTA2NDIx',
		avatar_url: 'https://avatars.githubusercontent.com/u/29506421?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Saurabstha',
		html_url: 'https://github.com/Saurabstha',
		followers_url: 'https://api.github.com/users/Saurabstha/followers',
		following_url:
			'https://api.github.com/users/Saurabstha/following{/other_user}',
		gists_url: 'https://api.github.com/users/Saurabstha/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/Saurabstha/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/Saurabstha/subscriptions',
		organizations_url: 'https://api.github.com/users/Saurabstha/orgs',
		repos_url: 'https://api.github.com/users/Saurabstha/repos',
		events_url: 'https://api.github.com/users/Saurabstha/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/Saurabstha/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'itsmeganeshadhikari',
		id: 33726734,
		node_id: 'MDQ6VXNlcjMzNzI2NzM0',
		avatar_url: 'https://avatars.githubusercontent.com/u/33726734?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/itsmeganeshadhikari',
		html_url: 'https://github.com/itsmeganeshadhikari',
		followers_url: 'https://api.github.com/users/itsmeganeshadhikari/followers',
		following_url:
			'https://api.github.com/users/itsmeganeshadhikari/following{/other_user}',
		gists_url:
			'https://api.github.com/users/itsmeganeshadhikari/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/itsmeganeshadhikari/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/itsmeganeshadhikari/subscriptions',
		organizations_url: 'https://api.github.com/users/itsmeganeshadhikari/orgs',
		repos_url: 'https://api.github.com/users/itsmeganeshadhikari/repos',
		events_url:
			'https://api.github.com/users/itsmeganeshadhikari/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/itsmeganeshadhikari/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'achalshail',
		id: 40120475,
		node_id: 'MDQ6VXNlcjQwMTIwNDc1',
		avatar_url: 'https://avatars.githubusercontent.com/u/40120475?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/achalshail',
		html_url: 'https://github.com/achalshail',
		followers_url: 'https://api.github.com/users/achalshail/followers',
		following_url:
			'https://api.github.com/users/achalshail/following{/other_user}',
		gists_url: 'https://api.github.com/users/achalshail/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/achalshail/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/achalshail/subscriptions',
		organizations_url: 'https://api.github.com/users/achalshail/orgs',
		repos_url: 'https://api.github.com/users/achalshail/repos',
		events_url: 'https://api.github.com/users/achalshail/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/achalshail/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'AbhishekGupta0762',
		id: 47381470,
		node_id: 'MDQ6VXNlcjQ3MzgxNDcw',
		avatar_url: 'https://avatars.githubusercontent.com/u/47381470?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/AbhishekGupta0762',
		html_url: 'https://github.com/AbhishekGupta0762',
		followers_url: 'https://api.github.com/users/AbhishekGupta0762/followers',
		following_url:
			'https://api.github.com/users/AbhishekGupta0762/following{/other_user}',
		gists_url: 'https://api.github.com/users/AbhishekGupta0762/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/AbhishekGupta0762/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/AbhishekGupta0762/subscriptions',
		organizations_url: 'https://api.github.com/users/AbhishekGupta0762/orgs',
		repos_url: 'https://api.github.com/users/AbhishekGupta0762/repos',
		events_url:
			'https://api.github.com/users/AbhishekGupta0762/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/AbhishekGupta0762/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'Upsyco08',
		id: 53856036,
		node_id: 'MDQ6VXNlcjUzODU2MDM2',
		avatar_url: 'https://avatars.githubusercontent.com/u/53856036?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Upsyco08',
		html_url: 'https://github.com/Upsyco08',
		followers_url: 'https://api.github.com/users/Upsyco08/followers',
		following_url:
			'https://api.github.com/users/Upsyco08/following{/other_user}',
		gists_url: 'https://api.github.com/users/Upsyco08/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/Upsyco08/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/Upsyco08/subscriptions',
		organizations_url: 'https://api.github.com/users/Upsyco08/orgs',
		repos_url: 'https://api.github.com/users/Upsyco08/repos',
		events_url: 'https://api.github.com/users/Upsyco08/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/Upsyco08/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'zyn-thakur',
		id: 58027726,
		node_id: 'MDQ6VXNlcjU4MDI3NzI2',
		avatar_url: 'https://avatars.githubusercontent.com/u/58027726?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/zyn-thakur',
		html_url: 'https://github.com/zyn-thakur',
		followers_url: 'https://api.github.com/users/zyn-thakur/followers',
		following_url:
			'https://api.github.com/users/zyn-thakur/following{/other_user}',
		gists_url: 'https://api.github.com/users/zyn-thakur/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/zyn-thakur/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/zyn-thakur/subscriptions',
		organizations_url: 'https://api.github.com/users/zyn-thakur/orgs',
		repos_url: 'https://api.github.com/users/zyn-thakur/repos',
		events_url: 'https://api.github.com/users/zyn-thakur/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/zyn-thakur/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'Sudekshasingh',
		id: 58876555,
		node_id: 'MDQ6VXNlcjU4ODc2NTU1',
		avatar_url: 'https://avatars.githubusercontent.com/u/58876555?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Sudekshasingh',
		html_url: 'https://github.com/Sudekshasingh',
		followers_url: 'https://api.github.com/users/Sudekshasingh/followers',
		following_url:
			'https://api.github.com/users/Sudekshasingh/following{/other_user}',
		gists_url: 'https://api.github.com/users/Sudekshasingh/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/Sudekshasingh/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/Sudekshasingh/subscriptions',
		organizations_url: 'https://api.github.com/users/Sudekshasingh/orgs',
		repos_url: 'https://api.github.com/users/Sudekshasingh/repos',
		events_url: 'https://api.github.com/users/Sudekshasingh/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/Sudekshasingh/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'pujaaryal89',
		id: 60313200,
		node_id: 'MDQ6VXNlcjYwMzEzMjAw',
		avatar_url: 'https://avatars.githubusercontent.com/u/60313200?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/pujaaryal89',
		html_url: 'https://github.com/pujaaryal89',
		followers_url: 'https://api.github.com/users/pujaaryal89/followers',
		following_url:
			'https://api.github.com/users/pujaaryal89/following{/other_user}',
		gists_url: 'https://api.github.com/users/pujaaryal89/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/pujaaryal89/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/pujaaryal89/subscriptions',
		organizations_url: 'https://api.github.com/users/pujaaryal89/orgs',
		repos_url: 'https://api.github.com/users/pujaaryal89/repos',
		events_url: 'https://api.github.com/users/pujaaryal89/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/pujaaryal89/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'sanjayhamal',
		id: 66766529,
		node_id: 'MDQ6VXNlcjY2NzY2NTI5',
		avatar_url: 'https://avatars.githubusercontent.com/u/66766529?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/sanjayhamal',
		html_url: 'https://github.com/sanjayhamal',
		followers_url: 'https://api.github.com/users/sanjayhamal/followers',
		following_url:
			'https://api.github.com/users/sanjayhamal/following{/other_user}',
		gists_url: 'https://api.github.com/users/sanjayhamal/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/sanjayhamal/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/sanjayhamal/subscriptions',
		organizations_url: 'https://api.github.com/users/sanjayhamal/orgs',
		repos_url: 'https://api.github.com/users/sanjayhamal/repos',
		events_url: 'https://api.github.com/users/sanjayhamal/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/sanjayhamal/received_events',
		type: 'User',
		site_admin: false,
	},
]
